- name: Data Types
  hosts: localhost
  vars: 
    NAME: Prem # Key Value
    Skills: # Skill is a LIST Type
     - DevOps
     - AWS
     - ANsible 
     - Linux
     - Windows Admin
    Experience: # Experience is MAP type. It contains key value
       DevOps: 7
       AWS: 2
       Docker: 4
    Trainer: true # BOOLEAN type
  tasks:
  - name: Print Key Value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: Print LIST
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: Print MAP
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: Print Key BOOLEAN
    ansible.builtin.debug:
      msg: "Trainer: {{Trainer}}"

      